### ISSUE TITLE
skip meatabase install wizard

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-metabase#10]
**Describe the bug**

use [setup API](https://www.metabase.com/learn/administration/serialization#add-users-to-our-metabase-origin-environment) to skip meatabase install wizard

**Comment by chendelin1982** [comment]
Done

**Comment by qiaofeng1227** [comment]
```
2022-01-11 14:59:16,067 ERROR metabase.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Unable to connect to Metabase mysql DB. {}
	at metabase.db.setup$fn__33730$verify_db_connection__33735$fn__33736$fn__33737.invoke(setup.clj:102)
	at metabase.db.setup$fn__33730$verify_db_connection__33735$fn__33736.invoke(setup.clj:100)
	at metabase.db.setup$fn__33730$verify_db_connection__33735.invoke(setup.clj:94)
	at metabase.db.setup$setup_db_BANG_$fn__33765$fn__33766.invoke(setup.clj:142)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:693)
	at metabase.util$do_with_us_locale.invoke(util.clj:679)
	at metabase.db.setup$setup_db_BANG_$fn__33765.invoke(setup.clj:141)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)
	at metabase.db$setup_db_BANG_$fn__33873.invoke(db.clj:61)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)
	at metabase.db$setup_db_BANG_.invoke(db.clj:51)
	at metabase.core$init_BANG_.invokeStatic(core.clj:91)
	at metabase.core$init_BANG_.invoke(core.clj:74)
	at metabase.core$start_normally.invokeStatic(core.clj:135)
	at metabase.core$start_normally.invoke(core.clj:129)
	at metabase.core$_main.invokeStatic(core.clj:168)
	at metabase.core$_main.doInvoke(core.clj:162)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
```
